# Generated by Django 3.2.15 on 2022-10-10 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsrecipe',
            name='tag',
            field=models.ForeignKey(help_text='Тэг рецепта', on_delete=django.db.models.deletion.CASCADE, to='tags.tag', verbose_name='Тэг рецепта'),
        ),
    ]
