# Generated by Django 3.2.15 on 2022-10-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_tagsrecipe_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsrecipe',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tag', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
