# Generated by Django 3.2.15 on 2022-10-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tagsrecipe_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='unique_ingredient',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_name_author',
        ),
        migrations.RemoveConstraint(
            model_name='tagsrecipe',
            name='unique_tag',
        ),
    ]
