# Generated by Django 3.2.15 on 2022-10-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221012_0843'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipes',
            name='unique_favorite_recipes',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shoppinglist_recipe',
        ),
    ]
